name: Generate pacman animation

on:
  schedule:       # runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # allows manual runs from the Actions tab
  push:
    branches:
      - main

jobs:
  generate:
    # Give write permission so the job can push the generated files
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          fill_color: "#FF69B4"   # Pacman - hot pink
          empty_color: "#000000"  # Empty squares - black (acts as background)
          ghost_color: "#FFB6C1"  # Ghosts - light pink
          dot_color: "#FFC0CB"    # Dots - classic pink

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
